### ISSUE TITLE
What type of device are you using now?

### ISSUE THREAD

**Issue by rench** [nxhack/openwrt-yun-build-extra#1]
What type of device are you using now?

**Comment by nxhack** [comment]
This branch literally targets "Arduino Yun".

https://store.arduino.cc/usa/arduino-yun
http://www.arduino.org/products/boards/arduino-yun
http://www.linino.org/product/arduino-yun/

As you know, Arduino is famous as a learning environment for microcomputers.
In addition to Arduino 's MPU, the Yun series is equipped with a CPU running a modern operating system, making it ideal for prototyping, especially for IoT applications.

However, the OS version provided by the vendor is old, so I am doing this work to rebuild with the latest OpenWrt / LEDE.

**Comment by rench** [comment]
Well, I see.
I see you a lot of projects are related to LEDE or OpenWrt,are you engaged in the development of router-related work Or hobbies? Do you have a more recommended device for building a smart home control center?

**Comment by nxhack** [comment]
> are you engaged in the development of router-related work Or hobbies? 

I am just a hobbyist. ;)

> Do you have a more recommended device for building a smart home control center?

From the view of convenience of building Internet applications, I recommend the Raspberry Pi series.
