### ISSUE TITLE
Can't open luci webpanel

### ISSUE THREAD

**Issue by scenaristeur** [nxhack/openwrt-yun-build-extra#3]
Hello @nxhack, now, i've build openwrt 18.06 with openwrt-yun-build-extra (without alljoyn ;-)

http://192.168.1.1
can't find luci/webpanel/homepage

& when I open http://192.168.1.1/cgi-bin/luci or http://192.168.1.1/arduino

I got 

?:0: attempt to index field 'authenticator' (a nil value)
stack traceback:
	?: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:614: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:262: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

Do you have any idea ?

I don't know lua programming, but it seems that at this point there is a v(), and at other there is v.func() ??

edit : I don't know if this can change something, but my lang is 'fr' & not 'en'

**Comment by nxhack** [comment]
@scenaristeur 

Thank you for your report.

Is this line in ""/etc/config/uhttpd" ?
```
	list alias '/arduino=/cgi-bin/luci'
	list alias '/data=/cgi-bin/luci'
	list alias '/mailbox=/cgi-bin/luci'
```

**Comment by scenaristeur** [comment]
Yes , here is my uhttpd : 

config uhttpd 'main'
	list listen_http '0.0.0.0:80'
	list listen_http '[::]:80'
	list listen_https '0.0.0.0:443'
	list listen_https '[::]:443'
	option home '/www'
	option rfc1918_filter '0'
	option max_requests '3'
	option max_connections '100'
	option cert '/etc/uhttpd.crt'
	option key '/etc/uhttpd.key'
	option cgi_prefix '/cgi-bin'
	option script_timeout '60'
	option network_timeout '30'
	option http_keepalive '20'
	option tcp_keepalive '1'
	option ubus_prefix '/ubus'
	list alias '/arduino=/cgi-bin/luci'
	list alias '/data=/cgi-bin/luci'
	list alias '/mailbox=/cgi-bin/luci'
	option redirect_https '0'

config cert 'px5g'
	option days '36500'
	option bits '1024'
	option country 'IT'
	option state 'Turin'
	option location 'Turin'
	option commonname 'Arduino LLC'

reinstalling luci from lede repo,  the problem is always here 
insdtalling arduinoos : 


config uhttpd 'main'
	list listen_http '0.0.0.0:80'
	list listen_http '[::]:80'
	list listen_https '0.0.0.0:443'
	list listen_https '[::]:443'
	option redirect_https '1'
	option home '/osjs/dist'
	option rfc1918_filter '1'
	option max_requests '3'
	option max_connections '100'
	option cert '/etc/uhttpd.crt'
	option key '/etc/uhttpd.key'
	option cgi_prefix '/cgi-bin'
	list lua_prefix '/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
	option script_timeout '60'
	option network_timeout '30'
	option http_keepalive '20'
	option tcp_keepalive '1'
	option ubus_prefix '/ubus'

config cert 'defaults'
	option days '730'
	option bits '2048'
	option country 'ZZ'
	option state 'Somewhere'
	option location 'Unknown'
	option commonname 'OpenWrt'

I can install Arduinoos (the green osjs version) and it looks good, but in arduinnoos , the link to luci give me the same thing : 

/usr/lib/lua/luci/controller/linino/index.lua:144: attempt to index field 'authenticator' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/linino/index.lua:144: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:614: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:262: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by nxhack** [comment]
https://github.com/arduino/lede-yun/commit/565508f99cc8922d55b47554de98f7dcb441a461

It seems that there is a problem with the latest luci.

**Comment by nxhack** [comment]
https://github.com/openwrt/luci/issues/2098

It seems there are hints here.

> This is due to the fact that LuCI on 17.01 had its own user authentication code directly checking /etc/shadow while LuCI on 18.06 switched to in-memory ubus based sessions provided by rpcd.

**Comment by nxhack** [comment]
I changed to the luci lede-17.01 branch and confirmed that it is working.

I will check more.

**Comment by scenaristeur** [comment]
Ok thx, i've tried to build lede-17-01 but today it was blocked with expat ? / expact ? module, i'll build 17 again soon ;-) 
Great job, I wish I could soon install my [lininoapps](https://github.com/scenaristeur/lininoapps) again with node10
